"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
palette = 'tokyonight'

format = """
$directory\
$git_branch\
$git_status\
$nodejs$python$rust$golang$c\
$cmd_duration\
$line_break\
$character"""

right_format = """$time"""

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true
read_only = "  "
format = "[ $path ]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = " "
style = "bold mauve"
format = "[$symbol$branch ]($style)"

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style) )"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vimcmd_symbol = "[](bold yellow)"

[cmd_duration]
min_time = 500
style = "bold yellow"
format = "[ $duration]($style) "

[time]
disabled = false
format = "[  $time ]($style)"
style = "bold subtext"
time_format = "%H:%M"

[nodejs]
symbol = " "
style = "bold green"
[python]
symbol = " "
style = "bold yellow"
[rust]
symbol = " "
style = "bold peach"
[golang]
symbol = " "
style = "bold sapphire"
[c]
symbol = " "
style = "bold blue"

[palettes.tokyonight]
rosewater = "#c0caf5"
flamingo  = "#ff9e64"
pink      = "#bb9af7"
mauve     = "#bb9af7"
red       = "#f7768e"
maroon    = "#ff9e64"
peach     = "#ff9e64"
yellow    = "#e0af68"
green     = "#9ece6a"
teal      = "#2ac3de"
sky       = "#7dcfff"
sapphire  = "#2ac3de"
blue      = "#7aa2f7"
lavender  = "#bb9af7"
text      = "#c0caf5"
subtext   = "#a9b1d6"
overlay   = "#565f89"
surface2  = "#545c7e"
surface1  = "#414868"
surface0  = "#292e42"
base      = "#1a1b26"
mantle    = "#16161e"
crust     = "#15161e"
