# Autostart — processi avviati con Hyprland
exec-once = waybar
exec-once = mako

# Da aggiungere man mano che installiamo:
# exec-once = swww-daemon          # wallpaper (Fase 5)
# exec-once = hypridle             # idle (Fase 8)
# exec-once = wl-paste --watch cliphist store   # clipboard (Fase 3)
# exec-once = hyprpolkitagent      # autenticazione grafica
